# Generated by Django 4.2.30 on 2026-07-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filiale',
            fields=[
                ('id_filiale', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nom_filiale', models.CharField(max_length=200)),
                ('pays', models.CharField(blank=True, max_length=20, null=True)),
                ('etat_activation', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'filiale',
                'ordering': ['nom_filiale'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id_fournisseur', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_fournisseur', models.TextField()),
                ('gsm_fournisseur', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'fournisseur',
                'ordering': ['nom_fournisseur'],
            },
        ),
        migrations.CreateModel(
            name='GAB',
            fields=[
                ('terminal', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_serie', models.CharField(max_length=50)),
                ('nom_gab', models.CharField(max_length=150)),
                ('date_installation', models.CharField(max_length=50)),
                ('emplacement', models.CharField(max_length=200)),
                ('type_emplacement', models.CharField(max_length=200)),
                ('gestion', models.IntegerField()),
                ('gestionnaire', models.CharField(max_length=200)),
                ('ip_adresse_gab', models.CharField(max_length=150)),
                ('ip_adresse_source', models.CharField(max_length=150)),
                ('type_gab', models.CharField(max_length=15)),
                ('code_bank', models.CharField(max_length=10)),
                ('code_bam', models.IntegerField()),
                ('code_group', models.CharField(max_length=200)),
                ('code_succursale', models.CharField(max_length=10)),
                ('code_agence', models.CharField(max_length=10)),
                ('libelle_agence', models.CharField(max_length=150)),
                ('adresse_gab', models.TextField()),
                ('importance', models.CharField(max_length=2)),
                ('ville', models.CharField(max_length=50)),
                ('id_activation', models.IntegerField()),
                ('etat', models.CharField(choices=[('OPERATIONNEL', 'Opérationnel'), ('HORS_SERVICE', 'Hors service'), ('CRITIQUE', 'Critique'), ('PASSIF', 'Passif'), ('SUPERVISION', 'En supervision')], default='PASSIF', max_length=20)),
                ('derniere_synchronisation', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(db_column='id_fournisseur', on_delete=django.db.models.deletion.PROTECT, related_name='gabs', to='gab.fournisseur')),
            ],
            options={
                'db_table': 'gab',
                'ordering': ['terminal'],
            },
        ),
    ]
