# Generated by Django 4.2.30 on 2026-07-10 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filiale',
            options={'ordering': ['nom_filiale'], 'verbose_name': 'Filiale', 'verbose_name_plural': 'Filiales'},
        ),
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'ordering': ['nom_fournisseur'], 'verbose_name': 'Fournisseur', 'verbose_name_plural': 'Fournisseurs'},
        ),
        migrations.AlterModelOptions(
            name='gab',
            options={'ordering': ['terminal'], 'verbose_name': 'GAB', 'verbose_name_plural': 'GAB'},
        ),
        migrations.AlterField(
            model_name='filiale',
            name='etat_activation',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gab',
            name='adresse_gab',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gab',
            name='code_agence',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gab',
            name='code_bam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gab',
            name='code_bank',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gab',
            name='code_group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gab',
            name='code_succursale',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gab',
            name='date_installation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gab',
            name='emplacement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gab',
            name='fournisseur',
            field=models.ForeignKey(blank=True, db_column='id_fournisseur', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gabs', to='gab.fournisseur'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='gestion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gab',
            name='gestionnaire',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gab',
            name='id_activation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gab',
            name='importance',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='gab',
            name='ip_adresse_gab',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='gab',
            name='ip_adresse_source',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='gab',
            name='libelle_agence',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='gab',
            name='nom_gab',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='gab',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gab',
            name='type_emplacement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gab',
            name='type_gab',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='gab',
            name='ville',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
