# Generated by Django 4.2.30 on 2026-07-18 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Destinataire',
                'verbose_name_plural': 'Destinataires',
                'ordering': ['nom', 'email'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre')),
                ('type_rapport', models.CharField(choices=[('QUOTIDIEN', 'Quotidien'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel'), ('ANNUEL', 'Annuel'), ('PERSONNALISE', 'Personnalisé')], max_length=20, verbose_name='Type')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('EMAIL', 'E-mail')], default='PDF', max_length=10, verbose_name='Format')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('GENERATION', 'En génération'), ('GENERE', 'Généré'), ('ECHEC', 'Échec'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('parametres', models.JSONField(blank=True, default=dict, help_text='Filtres et options de génération sérialisés.', verbose_name='Paramètres')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_generation', models.DateTimeField(blank=True, null=True, verbose_name='Date de génération')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé'), ('ECHEC', 'Échec'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20, verbose_name="Statut d'envoi")),
                ('sujet', models.CharField(blank=True, max_length=255, verbose_name='Sujet')),
                ('message_erreur', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('reponse_smtp', models.TextField(blank=True, help_text='Détail technique de la passerelle de messagerie.', verbose_name='Réponse SMTP')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('date_echec', models.DateTimeField(blank=True, null=True, verbose_name="Date d'échec")),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='rapports.destinataire', verbose_name='Destinataire')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='rapports.rapport', verbose_name='Rapport')),
            ],
            options={
                'verbose_name': "Journal d'envoi e-mail",
                'verbose_name_plural': "Journaux d'envoi e-mail",
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.AddConstraint(
            model_name='destinataire',
            constraint=models.UniqueConstraint(fields=('email',), name='uq_destinataire_email'),
        ),
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['type_rapport', 'statut'], name='idx_rapport_type_statut'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['statut'], name='idx_emaillog_statut'),
        ),
    ]
